/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Backend: typeof import('./src/components/Backend.vue')['default']
    CategoryList: typeof import('./src/components/admin/CategoryList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    GoodsList: typeof import('./src/components/admin/GoodsList.vue')['default']
    IEpGoods: typeof import('~icons/ep/goods')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMessage: typeof import('~icons/ep/message')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpShop: typeof import('~icons/ep/shop')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    Index: typeof import('./src/components/admin/Index.vue')['default']
    Info: typeof import('./src/components/admin/Info.vue')['default']
    LoginAdmin: typeof import('./src/components/LoginAdmin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./src/components/admin/UserList.vue')['default']
  }
}
